# Generated by Django 4.2.1 on 2023-05-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FestivalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='date',
            field=models.IntegerField(verbose_name='DATE'),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='decription',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PRICE'),
        ),
        migrations.AlterField(
            model_name='pub',
            name='date',
            field=models.IntegerField(verbose_name='DATE'),
        ),
        migrations.AlterField(
            model_name='pub',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DESCRIPTION'),
        ),
    ]
