# Generated by Django 4.2.1 on 2023-05-10 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FestivalApp', '0002_alter_club_date_alter_club_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='pub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FestivalApp.pub'),
        ),
    ]
