# Generated by Django 4.2.1 on 2023-05-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FestivalApp', '0003_remove_pub_menu_menu_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='belong',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BELONG'),
        ),
    ]
